### ISSUE TITLE
Update for React 16.x

### ISSUE THREAD

**Issue by laurence-hudson-tessella** [nearengine/react-delay#1]
Using `react-delay` in the latest react (`15.5.0`) produces the following warning.
`Warning: Delay: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`
Would be good to get out in front of this and fix pre 16.x stable.

**Comment by laurence-hudson-tessella** [comment]
Will submit a PR later in the week, time permitting.

**Comment by laurence-hudson-tessella** [comment]
Should probably update for `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead` at the same time.

**Comment by hafen** [comment]
I see a PR here to address this. Will this be merged in soon?

**Comment by chrisshiplet** [comment]
I'm so sorry this took so long to get published! You should see it on NPM as v0.0.4 now. To be honest I didn't know people were using this, so I'll try to keep a closer eye on it in the future :flushed:

**Comment by laurence-hudson-tessella** [comment]
Thanks @chrisshiplet.

**Comment by chrisshiplet** [comment]
No problem. I'll still be investigating publishing a 1.0.0 with some better NPM practices - but I haven't had time to get around to researching it yet. Thanks for the contribution!
