### ISSUE TITLE
No delay after parent update

### ISSUE THREAD

**Issue by V-for-Vaggelis** [nearengine/react-delay#8]
The delay works perfect on page load, but it will not work when the parent component is updated via the setState method. Is it built to work like that or am I missing something here?

**Comment by chrisshiplet** [comment]
The component only sets a timer on mount right now. When `setState` runs in your parent component, the Delay component won't be re-mounted, only re-rendered. If you wanted to force this component to re-mount every time a parent's state changes, you could add a `key` prop to the Delay component with the value of state you want to watch like this:

```
<Delay wait={250} key={this.state.someValueThatChanges}>
  <div>Hello, world</div>
</Delay>
```

Now each time `state.someValueThatChanges` changes, the Delay timer will be restarted.

**Comment by V-for-Vaggelis** [comment]
Thanks for the response. Just tried it and works like a charm. However I managed to achieve desired results with some timeouts. Might be more practical here cause I also want some animations to run during the delay. I'll definetly keep your insights in mind for any future use though 😃

**Comment by chrisshiplet** [comment]
No problem! This component is just a simple little `setTimeout` under the hood 😄 If you have some more complex interactions to put together, you're probably better off rolling your own. My original use case for this component is basically delaying a loading spinner to prevent flicker on components that load really fast most of the time, which is super simple.

**Comment by V-for-Vaggelis** [comment]
Nice, what I am actually doing, is building an interactive portfolio with react. So I am trying to simulate a live conversation between me and the user. I ask him some questions and he gets a suitable response depending on his actions. I want to delay those responses with some animations (like some dots jumping around) to make it look like I am responding in real time and create a more live experience.
